 name: "Project Quay Pull Request Action"
 on: pull_request
 jobs:
    projquay_pr_action:
        runs-on: ubuntu-latest
        steps:
        - uses: thomasmckay/projquay-pr-action@working
          with:
              repo-token: "${{ secrets.GITHUB_TOKEN }}"
              branch-regex: ".+"
